FROM node:20-alpine as angular
WORKDIR /app
COPY package*.json .
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:alpine
ARG name
COPY --from=angular /front-test/dist/$name/browser /usr/share/nginx/html
EXPOSE 80